:uat:
  host: test.salesforce.com
  username: admintestuser@thoughtworks.com.sfdcuat2
  password: passw0rddnDXy3PT7y90Ao8kmCR1TPeVw
  client_secret: 1179530895450605826
  client_id: 3MVG9Iu66FKeHhIMhqAqgK7P.OEaYdDvpQue.0Fy_KIIyrxXwkItHvPUVFN987AIYtM1I8e6sxo08EwaY84Za
  instance_url: https://test.salesforce.com/services/oauth2/token
  url: https://cs2.salesforce.com



